
export const SEND_CHAT_MESSAGE_REQUEST = 'SEND_CHAT_MESSAGE_REQUEST';
export const SEND_CHAT_MESSAGE_SUCCESS = 'SEND_CHAT_MESSAGE_SUCCESS';
export const SEND_CHAT_MESSAGE_FAILURE = 'SEND_CHAT_MESSAGE_FAILURE';
export const CLEAR_CHAT_RESPONSE = 'CLEAR_CHAT_RESPONSE';
export const CLEAR_CHAT_ERROR = 'CLEAR_CHAT_ERROR';