export const REGISTER_REQUEST = "REGISTER_REQUEST"; 
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILIURE = "REGISTER_FAILIURE";  

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";   
export const LOGIN_FAILIURE = "LOGIN_FAILIURE";

export const LOGIN_TWO_STEP_REQUEST = "LOGIN_TWO_STEP_REQUEST";
export const LOGIN_TWO_STEP_SUCCESS = "LOGIN_TWO_STEP_SUCCESS";
export const LOGIN_TWO_STEP_FAILIURE = "LOGIN_TWO_STEP_FAILIURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST"; 
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILIURE = "GET_USER_FAILIURE";

export const SEND_VERIFICATION_OTP_REQUEST = "SEND_VERIFICATION_OTP_REQUEST";
export const SEND_VERIFICATION_OTP_SUCCESS = "SEND_VERIFICATION_OTP_SUCCESS";
export const SEND_VERIFICATION_OTP_FAILIURE = "SEND_VERIFICATION_OTP_FAILIURE";


export const ENABLE_TWO_STEP_AUTHENTICATION_REQUEST = "ENABLE_TWO_STEP_AUTHENTICATION_REQUEST";
export const ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS = "ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS";
export const ENABLE_TWO_STEP_AUTHENTICATION_FAILIURE = "ENABLE_TWO_STEP_AUTHENTICATION_FAILIURE";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILIURE = "VERIFY_OTP_FAILIURE";

export const SEND_RESET_PASSWORD_REQUEST = "SEND_RESET_PASSWORD_REQUEST";
export const SEND_RESET_PASSWORD_SUCCESS = "SEND_RESET_PASSWORD_SUCCESS";
export const SEND_RESET_PASSWORD_FAILIURE = "SEND_RESET_PASSWORD_FAILIURE";

export const VERIFY_RESET_PASSWORD_REQUEST = "VERIFY_RESET_PASSWORD_REQUEST";
export const VERIFY_RESET_PASSWORD_SUCCESS = "VERIFY_RESET_PASSWORD_SUCCESS";
export const VERIFY_RESET_PASSWORD_FAILIURE = "VERIFY_RESET_PASSWORD_FAILIURE";

export const LOGOUT="LOGOUT";